image: ubuntu

stages:
- deploy

before_script:
# install ssh-agent
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
- eval $(ssh-agent -s)

#add private ky to agent store
- echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

# create ~/.ssh folder
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh


- ssh-keyscan 209.250.238.165 >> ~/.ssh/known_hosts
- chmod 644 ~/.ssh/known_hosts

deploy_:
  stage: deploy
  environment: Staging
  only:
  - master
  script:
  # connect to server
  - ssh hansidep@209.250.238.165 "rm -rf * && git clone https://github.com/christophschnabl/marky.git && cd marky && docker-compose build && docker-compose up && exit"