image: docker:latest

variables:
  DOCKER_IMAGE_TAGGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

services:
- docker:dind

stages:
- build

before_script:
- apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
- pip install docker-compose

build_images:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose build
    - docker-compose push matthiasreumann/marky:$DOCKER_IMAGE_TAGGED

