variables:
  DOCKER_IMAGE_TAGGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

stages:
- build

build_images:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose build
    - docker-compose push matthiasreumann/marky:$DOCKER_IMAGE_TAGGED

