image: node:latest

stages:
- build

cache:
  paths:
  - server/node_modules/
  - frontend/node_modules/

build_server:
  stage: build
  script:
  - cd server/
  - npm install
  artifacts:
    paths:
    - server/node_modules/

build_frontend:
  stage: build
  script:
  - cd frontend/
  - npm install
  artifacts:
    paths:
    - frontend/node_modules/


